# Generated by Django 3.1.6 on 2021-02-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default='exit'),
            preserve_default=False,
        ),
    ]
