# Generated by Django 3.1.6 on 2021-03-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
    ]
